### ISSUE TITLE
UIをデザイン

### ISSUE THREAD

**Issue by uwatcha** [kCatMaker/SINKEN_TODO#3]

**Comment by uwatcha** [comment]
# Why
ユーザーがTODOアプリを使用するため
# What
アプリのUIをデザインする
Figmaを使用する

**Comment by kCatMaker** [comment]
【Figmaの参考】
自分が作ってるポートフォリオサイトでFigma使ってるやつ
https://www.figma.com/file/7DzGuEFvWgINyearCR4Rn8/kCat's-Portfolio?type=design&node-id=0%3A1&mode=design&t=x2krTJxkBwDF6pWn-1

**Comment by uwatcha** [comment]
figmaのリンク
https://www.figma.com/file/VZKPLdsCiVJ4Z8jFSH2CE8/Untitled?type=design&node-id=0-1&mode=design&t=4phgadBTTvmTaiN4-0

**Comment by uwatcha** [comment]
ものすごく無骨な見た目になっている。
丸みを持たせていきたい


![Image](https://github.com/kCat-fun/SINKEN_TODO/assets/105112595/109b42da-129a-462f-a6cc-9a575d7eea13)

**Comment by uwatcha** [comment]
# figmaの新しいリンク(2023/12/5)
https://www.figma.com/file/8V2egfndzX5oITYKvNOkXW/SINKEN_TODO_SAMPLE?type=design&node-id=1-2&mode=design&t=4Aps2BuWKyfBBkeZ-0

**Comment by uwatcha** [comment]
デザイン完了
指摘があれば適宜直します

**Comment by kCatMaker** [comment]
完成したので終了。

**Comment by uwatcha** [comment]
タスク追加ボタンを追加
